src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 * @UniqueEntity("name")
 * @Table(
 *     name="`user`",
 *     uniqueConstraints={
 *         @UniqueConstraint(name="email_unique",columns={"email"}),
 *         @UniqueConstraint(name="user_name_unique",columns={"name"}),
 *         @UniqueConstraint(name="user_twinoid_unique",columns={"twinoid_id"})
 *     }
 * )
 */
class User implements UserInterface, EquatableInterface
{

    const ROLE_USER      =  0;
    const ROLE_ORACLE    =  2;
    const ROLE_CROW      =  3;
    const ROLE_ADMIN     =  4;
    const ROLE_SUPER     =  5;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $pass;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validated;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\UserPendingValidation", mappedBy="user", cascade={"persist", "remove"})
     */
    private $pendingValidation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Citizen", mappedBy="user")
     */
    private $citizens;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdminBan", mappedBy="user")
     */
    private $bannings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FoundRolePlayText", mappedBy="user", cascade={"persist", "remove"})
     */
    private $foundTexts;

    /**
     * @ORM\Column(type="integer")
     */
    private $soulPoints = 0;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picto", mappedBy="user", cascade={"persist", "remove"})
     */
    private $pictos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Award", mappedBy="user")
     */
    private $awards;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $externalId = '';

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", cascade={"persist", "remove"})
     */
    private $avatar;

    /**
     * @ORM\Column(type="boolean")
     */
    private $preferSmallAvatars = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postAsDefault;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $forumTitle;

    /**
     * This field matches to the filename of the picto
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $forumIcon;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $language = null;

    /**
     * @ORM\Column(type="smallint")
     */
    private $rightsElevation = 0;

    /**
     * @ORM\OneToMany(targetEntity=CitizenRankingProxy::class, mappedBy="user", orphanRemoval=true)
     */
    private $pastLifes;

    /**
     * @ORM\Column(type="integer")
     */
    private $heroDaysSpent = 0;

    /**
     * @ORM\OneToOne(targetEntity=TwinoidImportPreview::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $twinoidImportPreview;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $twinoidID;

    /**
     * @ORM\OneToMany(targetEntity=TwinoidImport::class, mappedBy="user", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $twinoidImports;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $importedSoulPoints;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $importedHeroDaysSpent;

    /**
     * @ORM\ManyToOne(targetEntity=Changelog::class)
     */
    private $latestChangelog;

    /**
     * @ORM\OneToMany(targetEntity=ConnectionIdentifier::class, mappedBy="user", orphanRemoval=true)
     */
    private $connectionIdentifiers;

    /**
     * @ORM\OneToOne(targetEntity=ShadowBan::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $shadowBan;

    /**
     * @ORM\ManyToMany(targetEntity=ConnectionWhitelist::class, mappedBy="users", cascade={"persist", "remove"})
     */
    private $connectionWhitelists;

    public function __construct()
    {
        $this->citizens = new ArrayCollection();
        $this->foundTexts = new ArrayCollection();
        $this->pictos = new ArrayCollection();
        $this->bannings = new ArrayCollection();
        $this->pastLifes = new ArrayCollection();
        $this->twinoidImports = new ArrayCollection();
        $this->connectionIdentifiers = new ArrayCollection();
        $this->connectionWhitelists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getForumIcon(): ?string {
        return $this->forumIcon;
    }

    public function setForumIcon(string $value): self {
        $this->forumIcon = $value;

        return $this;
    }

    public function getForumTitle(): ?string {
        return $this->forumTitle;
    }

    public function setForumTitle(string $value): self {
        $this->forumTitle = $value;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSalt( ): string {
        return 'user_salt_myhordes_ffee45';
    }

    /**
     * @return Collection|AdminBan[]
     */
    public function getBannings(): Collection
    {
        return $this->bannings;
    }

    public function getValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getPendingValidation(): ?UserPendingValidation
    {
        return $this->pendingValidation;
    }

    public function setPendingValidation(?UserPendingValidation $pendingValidation): self
    {
        $this->pendingValidation = $pendingValidation;

        // set (or unset) the owning side of the relation if necessary
        $newUser = null === $pendingValidation ? null : $this;
        if ($pendingValidation && $pendingValidation->getUser() !== $newUser) {
            $pendingValidation->setUser($newUser);
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        $roles = [];
        if ($this->pass === null) return $roles;

        if     ($this->rightsElevation >= self::ROLE_SUPER)  $roles[] = 'ROLE_SUPER';
        elseif ($this->rightsElevation >= self::ROLE_ADMIN)  $roles[] = 'ROLE_ADMIN';
        elseif ($this->rightsElevation >= self::ROLE_CROW)   $roles[] = 'ROLE_CROW';
        elseif ($this->rightsElevation >= self::ROLE_ORACLE) $roles[] = 'ROLE_ORACLE';

        if (strstr($this->email, "@localhost") === "@localhost") $roles[] = 'ROLE_DUMMY';
        if ($this->email === 'crow') $roles[] = 'ROLE_CROW';

        if ($this->validated) $roles[] = 'ROLE_USER';
        else $roles[] = 'ROLE_REGISTERED';

        if ($this->getIsBanned()) $roles[] = 'ROLE_FORUM_BANNED';

        if ($this->getShadowBan()) $roles[] = 'ROLE_SHADOW_BANNED';

        return array_unique($roles);
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->pass;
    }

    public function setPassword(?string $pass): self {
        $this->pass = $pass;
        return $this;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials() {}

    /**
     * @inheritDoc
     */
    public function isEqualTo(UserInterface $user) {
        $b1 = $this->getPassword() !== null && $user->getPassword() !== null &&
            $this->getUsername() === $user->getUsername() &&
            $this->getPassword() === $user->getPassword() &&
            $this->getRoles() === $user->getRoles();
        if ($user instanceof User) {
            return $b1 &&
                $this->getRightsElevation() === $user->getRightsElevation();
        } else return $b1;
    }

    public function getIsBanned(): bool {
        foreach ($this->getBannings() as $b)
            if ($b->getActive())
                return true;
        return false;
    }

    public function getLongestActiveBan(): ?AdminBan {
        $ban = null;
        foreach ($this->getBannings() as $b){
            if ($b->getActive()) {
                if (!isset($ban)) {
                    $ban = $b;                       
                }
                else if ($b->getBanEnd() > $ban->getBanEnd())
                    $ban = $b;     
            }
        }            
        if (isset($ban))
            return $ban;
        return null;
    }

    /**
     * @return Collection|AdminBan[]
     */
    public function getActiveBans(): Collection {
        $bans = $this->getBannings();
        foreach ($bans as $ban){
                if (!($ban->getActive()))
                    $bans->remove($ban->getId());  
            }            
        return $bans;
    }

    public function getActiveCitizen(): ?Citizen {
        foreach ($this->getCitizens() as $c)
            if ($c->getActive())
                return $c;
        return null;

templates/ajax/admin/users/ban.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block ajax %}
    <div class="row soul">
        <div class="cell padded header rw-12">
            {% embed "ajax/admin/users/tabs.html.twig" %}{% endembed %}
            <div class="row">
                <div class="cell padded rw-3 rw-sm-12">
                    {{ 'Status'|trans({}, 'admin') }}
                </div>
                <div class="cell padded rw-5 rw-sm-12">
                    <input disabled style="width: 25em;" value="{% if banned %}{{ 'Verbannt bis '|trans({}, 'admin') }}{{ activeBan.banEnd|date('d.m.Y G:i:s') }}{% else %}{{ "--" }}{% endif %}" />
                </div>
                {% if banned %}
                <div class="cell padded rw-2 rw-sm-12">
                    <button id="x-lift-ban">{{ 'Aufheben'|trans({}, 'admin') }}</button>
                </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="cell padded rw-3 rw-sm-12">
                    {{ 'Letzte Verbannung'|trans({}, 'admin') }}
                </div>
                <div class="cell padded rw-5 rw-sm-12">
                    <input disabled style="width: 25em;" value="{% if banCount > 0 %}{{ lastBan.banStart|date('d.m.Y') }} -- {{ 'Verbannungen'|trans({}, 'admin') }}: {{ banCount }}{% else %}{{ "--" }}{% endif %}" />
                </div>
            </div>
            <div class="row">
                <div class="cell padded rw-3 rw-sm-12">
                    {{ 'Verbannen'|trans({}, 'admin') }}
                </div>
                <div class="cell padded rw-5 rw-sm-12">
                    <select name="duration" id="ban-duration">
                        <optgroup label={{ 'Dauer'|trans({}, 'admin') }}>
                            <option value="1">{{ '1 Tag'|trans({}, 'admin') }}</option>
                            <option value="3">{{ '3 Tage'|trans({}, 'admin') }}</option>
                            <option value="5">{{ '5 Tage'|trans({}, 'admin') }}</option>
                            <option value="7">{{ '7 Tage'|trans({}, 'admin') }}</option>
                            <option value="15">{{ '15 Tage'|trans({}, 'admin') }}</option>
                            <option value="30">{{ '30 Tage'|trans({}, 'admin') }}</option>
                        </optgroup>
                    </select>
                </div>
                <div class="row">
                    <div class="cell padded ro-2 rw-1 rw-sm-12">
                        {{ 'Grund'|trans({}, 'admin') }}
                    </div>
                    <div class="cell padded rw-5 rw-sm-12">
                        <textarea id="ban-reason"></textarea>                       
                    </div>
                </div>
                <div class="row">               
                    <div class="cell padded ro-3 rw-5 rw-sm-12">
                        <button id="x-confirm-ban">{{ 'Verbannen'|trans({}, 'admin') }}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% embed "ajax/admin/users/footer.html.twig" %}{% endembed %}
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
            document.getElementById('x-confirm-ban').addEventListener('click', function(e) {
            e.preventDefault();
            let target_payload = {                
                duration: document.getElementById('ban-duration').value,
                reason: document.getElementById('ban-reason').value,
            };

            $.ajax.easySend( '{{ path('admin_users_ban', { 'id': user.Id }) }}', target_payload,
                function () {
                    $.ajax.load(null, '{{ path('admin_users_ban_view', { 'id': user.Id }) }}', true);
                } )
        });
        {% if banned %}
        document.getElementById('x-lift-ban').addEventListener('click', function(e) {
            e.preventDefault();
            
            $.ajax.easySend( '{{ path('admin_users_ban_lift', { 'id': user.Id }) }}', [],
                function () {
                    $.ajax.load(null, '{{ path('admin_users_ban_view', { 'id': user.Id }) }}', true);
                } )
        });
        {% endif %}
    </script>
{% endblock %}

templates/ajax/admin/users/citizen.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block ajax %}
    <div class="row soul">
        <div class="cell padded header rw-12">
            {% embed "ajax/admin/users/tabs.html.twig" %}{% endembed %}

            <div class="row">
                <div class="cell rw-8 ro-2">
                    <div class="row">
                        <div class="cell padded rw-12">
                            {{ 'Derzeitiges Leben'|trans({}, 'admin') }}
                        </div>
                        <div class="cell padded rw-12">
                            <input disabled style="width: 25em;" value="{% if active %}{{ town.name }}{% if not alive %}{{ " -- " }}{{ 'TOD NICHT BESTÄTIGT'|trans({}, 'admin') }}{% endif %}{% else %}{{ "--" }}{% endif %}" />
                        </div>
                        {% if active %}
                            {% if alive %}
                                <div class="cell padded rw-4">
                                    <button id="x-headshot">{{ 'Kopfschuss'|trans({}, 'admin') }}</button>
                                </div>
                                <div class="cell padded rw-4">
                                    <button id="x-pm">{{ 'PM vom Raben'|trans({}, 'admin') }}</button>
                                </div>
                            {% else %}
                                {% if is_granted("ROLE_ADMIN") %}
                                    <div class="cell padded rw-4">
                                        <button id="x-confirm-death">{{ 'Tod bestätigen'|trans({}, 'admin') }}</button>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="cell padded rw-12">
                            <input type="hidden" id="pmidrecipient" value="{{ citizen_id }}">
                            <div id="forum-content">

                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
    {% embed "ajax/admin/users/footer.html.twig" %}{% endembed %}
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% if active %}
            {% if alive %}
                document.getElementById('x-headshot').addEventListener('click', function(e) {
                    e.preventDefault();
                    if (confirm('{{ 'Das Leben dieses Bürgers sofort beenden?'|trans({},'admin') }}'))
                        $.ajax.easySend( '{{ path('admin_users_citizen_headshot', { 'id': user.Id }) }}', [],
                            function () {
                                $.ajax.load(null, '{{ path('admin_users_citizen_view', { 'id': user.Id }) }}', true);
                            } )
                });

                document.getElementById('x-pm').addEventListener('click', function(e) {
                    document.getElementById("forum-content").innerHTML = "";
                    $.ajax.no_history().load( document.getElementById('forum-content'), '{{ path('admin_pm_editor_controller', {'type': 'pm'}) }}', false )
                });
            {% elseif is_granted("ROLE_ADMIN") %}
                document.getElementById('x-confirm-death').addEventListener('click', function(e) {
                    e.preventDefault();
                    if (confirm('{{ 'Tod dieses Bürgers zwangsweise bestätigen?'|trans({},'admin') }}'))
                        $.ajax.easySend( '{{ path('admin_users_citizen_confirm_death', { 'id': user.Id }) }}', [],
                            function () {
                                $.ajax.load(null, '{{ path('admin_users_citizen_view', { 'id': user.Id }) }}', true);
                            } )
                });
            {% endif %}
        {% endif %}


    </script>
{% endblock %}

templates/ajax/admin/users/footer.html.twig
<div class="row">
    <div class="cell padded rw-12 rw-sm-12">
        <div id="users-list-admin">
            <h5>{{'Suche:'|trans({}, "admin")}}</h5>
            <div><label><input type="text" id="user-search" style="margin-top: 5px; width: 20rem;" /></label><div class="tooltip help">{{ 'Gib den Pseudo des Bürgers ein.'|trans({},'soul') }}</div></div>
            <div id="users-list"></div>
        </div>
    </div>
</div>
{% block js %}
    <script>
        let typingTimer, doneTypingInterval = 500;
        let searchBox = document.getElementById('user-search');

        const userSearchHandler = function() {
            $.ajax.background().load(
                document.getElementById('users-list'),
                '{{ path('admin_users_fuzzyfind') }}',
                false,
                {'name': searchBox.value}
            );
        };

        const userSearchHandlerUp = function () {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(userSearchHandler, doneTypingInterval);
        };

        const userSearchHandlerDown = function () {
            clearTimeout(typingTimer);
        };

        searchBox.addEventListener('keyup', userSearchHandlerUp);
        searchBox.addEventListener('keydown', userSearchHandlerDown);
    </script>
{% endblock %}

templates/ajax/admin/users/index.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block ajax %}
    <div class="row">
        <div class="cell rw-12">
            <h5>{{'Multi-Account Report'|trans({}, "admin")}}</h5>
            <div class="row-table">
                <div class="row header">
                    <div class="cell padded rw-1">&nbsp;</div>
                    <div class="cell padded rw-3">{{ 'Benutzername'|trans({},'admin') }}</div>
                    <div class="cell padded rw-2">{{ 'Verdacht'|trans({},'admin') }}</div>
                    <div class="cell padded rw-6">{{ 'Andere Accounts'|trans({},'admin') }}</div>
                </div>
                {% for table in ma_report %}
                    {% if not table.principal.shadowBan %}
                    {# @var table \App\Structures\CheatTable #}
                        <div class="row">
                            <div class="cell rw-4 padded">
                                <b>{{ table.principal.username }}</b>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <br /><span>{{ table.principal.email }}</span>
                                {% endif %}
                            </div>
                            <div class="cell rw-2 padded">
                                {{ table.likeliness }}
                            </div>
                            <div class="cell {% if is_granted('ROLE_ADMIN') %}rw-5{% else %}rw-6{% endif %}">
                                {% set group = [] %}
                                {% for multi in table.users %}
                                    {% set group = group|merge([multi.id]) %}
                                    <span class="small pointer" x-whitelist-alt="{{ url('admin_users_account_view', {id: multi.id}) }}" x-whitelist="{{ group|join('|') }}" x-api-endpoint="{{ url('admin_users_account_manage', {action: 'whitelist', id: table.principal.id}) }}" {% if multi.shadowBan %}style="color:red; font-weight: bold"{% endif%} >
                                        {{ multi.username }}
                                        {% if is_granted('ROLE_ADMIN') %}
                                            <div class="tooltip">
                                                <i>({{ multi.id }})</i> <b>{{ multi.email }}</b>
                                                <hr/>
                                                <i>{{ 'Klick, um Profil in neuem Tab zu öffnen'|trans({},'admin') }}</i>
                                                <hr/>
                                                <i>{{ 'STRG+Klick, um zur Whitelist hinzuzufügen'|trans({},'admin') }}</i>
                                            </div>
                                        {% endif %}
                                    </span>&nbsp;
                                {% endfor %}
                            </div>
                            {% if is_granted('ROLE_ADMIN') %}
                                <div class="cell rw-1 padded">
                                    <button x-shadow x-api-endpoint="{{ url('admin_users_account_manage', {action: 'shadow',    id: table.principal.id}) }}">{{ 'Bann'|trans({},'admin') }}</button>
                                    <button x-whitelist="{{ group|join('|') }}" x-api-endpoint="{{ url('admin_users_account_manage', {action: 'whitelist', id: table.principal.id}) }}">{{ 'Whitelist'|trans({},'admin') }}</button>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

        </div>
    </div>
    {% embed "ajax/admin/users/footer.html.twig" %}{% endembed %}
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% if is_granted("ROLE_ADMIN") %}
            $.html.addEventListenerAll('[x-shadow][x-api-endpoint]', 'click', function(e,elem) {
                if (confirm("{{ 'Bestätigen?'|trans({},'global')|e('js') }}\nBAN"))
                    $.ajax.easySend( elem.getAttribute('x-api-endpoint'), {param: 'Multi Account'},
                        function () {
                            $.ajax.load(null, '{{ path('admin_users') }}', true);
                        } );
            });
        $.html.addEventListenerAll('[x-whitelist][x-api-endpoint]', 'click', function(e,elem) {
            if ((!elem.hasAttribute('x-whitelist-alt') || e.ctrlKey) && confirm("{{ 'Bestätigen?'|trans({},'global')|e('js') }}\nWHITELIST"))
                $.ajax.easySend( elem.getAttribute('x-api-endpoint'), {param: elem.getAttribute('x-whitelist').split('|')},
                    function () {
                        $.ajax.load(null, '{{ path('admin_users') }}', true);
                    } );
        });
        $.html.addEventListenerAll('[x-whitelist][x-whitelist-alt][x-api-endpoint]', 'click', function(e,elem) {
            if (!e.ctrlKey) window.open(elem.getAttribute('x-whitelist-alt'),'_blank');
        });
        {% endif %}
    </script>
{% endblock %}

templates/ajax/admin/users/list.html.twig
{% block ajax %}
    {% for user in users %}
        <div class="users-list-entry">
            <div x-ajax-href="{{ url('admin_users_citizen_view', {id: user.id}) }}" x-ajax-target="#content">
                <div class="avatar small"><img alt="" src="{{ user.avatar ? path('app_web_avatar', {'uid': user.id, 'name': user.avatar.smallName, 'ext': user.avatar.format}) : asset('build/images/forum/empty_avatar.gif') }}" style="margin-right: 0;"></div> {{ user.username }}
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/ajax/admin/users/pictos.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block ajax %}
    <div class="row soul">
        <div class="cell padded header rw-12">
            {% embed "ajax/admin/users/tabs.html.twig" %}{% endembed %}
            <div class="row">
                <div class="cell padded rw-12">
                    {{ 'Auszeichnungen'|trans({}, 'admin') }}
                </div>
                {% if is_granted("ROLE_ADMIN") %}
                {% set town = "" %}
                {% set i = 0 %}
                {% for picto in pictos %}
                    {% if i % 3 == 0 %}
                        DEBUT ROW
                    {% endif %}
                    {{ i }}
                    {% if not picto.town is null and picto.town.name != town %}
                        {% set i = i + 1 %}
                        {% set town = picto.town.name %}
                <div class="cell rw-5 rw-sm-12 distinctions">
                    <div class="distinctions-head center">
                        {{picto.town.name}}
                    </div>
                    <div class="distinctions-list center">
                        <div class="overall">
                            {{ '%points% Punkte'|trans({'%points%':0}, 'global') }}
                        </div>
                        <div class="list">
                    {% endif %}
                            <div class="picto{% if picto.prototype.rare %} rare{% endif %}">
                                <img src="{{  asset('build/images/pictos/' ~ picto.prototype.icon ~ '.gif') }}" /><br />
                                <div class="counter">
                                {% for number in picto.count|split('') %}
                                    <span class="count" title="{{number}}">{{number}}</span>
                                {% endfor %}
                                </div>
                                <div class="tooltip">
                                    <h1>{{ picto.prototype.label|trans({}, 'game') }}</h1>
                                    <em>{{ picto.prototype.description|trans({}, 'game')}}</em>
                                </div>
                            </div>
                    {% if loop.index0 == pictos|length - 1 or (not pictos[loop.index].town is null and pictos[loop.index].town.name != picto.town.name) %}
                        </div>
                    </div>
                    <div class="distinctions-foot">
                        &nbsp;
                    </div>
                </div>
                    {% endif %}
                    {% if i>0 and (i-1) % 3 == 2 %}
                        FIN ROW
                    {% endif %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    {% embed "ajax/admin/users/footer.html.twig" %}{% endembed %}
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% if is_granted("ROLE_ADMIN") %}

        {% endif %}
    </script>
{% endblock %}

templates/ajax/admin/users/tabs.html.twig
<div class="tabs">
    <div class="tab left inline">
        <h4 class="soul-name">
            {{ user.username }}
        </h4>
    </div>
    <div class="tab tab-floater">
        <div class="tab{% if admin_tab == "admin_users_account" %} selected{% endif %}">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('admin_users_account_view', { 'id': user.Id }) }}">{% trans from 'admin' %}Account{% endtrans %}</div>
        </div>
        <div class="tab{% if admin_tab == "admin_users_ban" %} selected{% endif %}">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('admin_users_ban_view', { 'id': user.Id }) }}">{% trans from 'admin' %}Verbannung{% endtrans %}</div>
        </div>
        <div class="tab{% if admin_tab == "admin_users_citizen" %} selected{% endif %}">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('admin_users_citizen_view', { 'id': user.Id }) }}">{% trans from 'admin' %}Bürger{% endtrans %}</div>
        </div>
        <!--<div class="tab{% if admin_tab == "admin_users_pictos" %} selected{% endif %}">
            <div class="tab-link" x-ajax-href="{{ path('admin_users_pictos_view', { 'id': user.Id }) }}">{% trans from 'admin' %}Auszeichnungen{% endtrans %}</div>
        </div>-->
    </div>

</div>